name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-homebrew-tap:
    runs-on: ubuntu-latest
    if: github.repository == 'peterlockett/copilot-jiratools'
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4

    - name: Extract version from tag
      id: version
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Download release assets
      run: |
        # Wait a moment for assets to be available
        sleep 30
        
        # Download checksums
        wget "https://github.com/peterlockett/copilot-jiratools/releases/download/v${{ steps.version.outputs.VERSION }}/checksums.txt"
        
        # Extract SHA256 values for macOS builds
        SHA256_X64=$(grep "osx-x64.tar.gz" checksums.txt | awk '{print $1}')
        SHA256_ARM64=$(grep "osx-arm64.tar.gz" checksums.txt | awk '{print $1}')
        
        echo "SHA256_X64=$SHA256_X64" >> $GITHUB_ENV
        echo "SHA256_ARM64=$SHA256_ARM64" >> $GITHUB_ENV

    - name: Update Homebrew formula
      run: |
        cat > Formula/jiratools.rb << EOF
        class Jiratools < Formula
          desc "A command-line tool for interacting with Jira from development environments"
          homepage "https://github.com/peterlockett/copilot-jiratools"
          version "${{ steps.version.outputs.VERSION }}"
          license "MIT"

          if Hardware::CPU.arm?
            url "https://github.com/peterlockett/copilot-jiratools/releases/download/v#{version}/jiratools-#{version}-osx-arm64.tar.gz"
            sha256 "${{ env.SHA256_ARM64 }}"
          else
            url "https://github.com/peterlockett/copilot-jiratools/releases/download/v#{version}/jiratools-#{version}-osx-x64.tar.gz"
            sha256 "${{ env.SHA256_X64 }}"
          end

          def install
            bin.install "jiratools"
          end

          test do
            assert_match "JiraTools", shell_output("#{bin}/jiratools --help")
          end
        end
        EOF

    - name: Checkout homebrew-tap repository
      uses: actions/checkout@v4
      with:
        repository: peterlockett/homebrew-tap
        token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        path: homebrew-tap

    - name: Update tap repository
      run: |
        # Copy updated formula
        cp Formula/jiratools.rb homebrew-tap/Formula/
        
        # Configure git
        cd homebrew-tap
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Commit and push
        git add Formula/jiratools.rb
        git commit -m "Update jiratools to v${{ steps.version.outputs.VERSION }}"
        git push

    - name: Test formula
      run: |
        cd homebrew-tap
        # Basic syntax check
        ruby -c Formula/jiratools.rb
